"""Modified User table - removed  email field

Revision ID: 4b7e95952d72
Revises: ff1eedeade36
Create Date: 2025-11-13 23:21:29.640367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7e95952d72'
down_revision: Union[str, Sequence[str], None] = 'ff1eedeade36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'environment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('environment', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
